Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.applicationinsights\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.authorization\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.hosting\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.http\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.mvc.core\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.mvc.versioning.swagger\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.serilog\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.aspnetcore.swagger\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.hosting\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.nservicebus\ -Recurse -ErrorAction SilentlyContinue 
Remove-Item $env:USERPROFILE\.nuget\packages\prospa.extensions.serilog\ -Recurse -ErrorAction SilentlyContinue 